sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product sqr-032
env:
  global:
    -
      # LTD_AWS_ID
      secure: criAU6NQz60AbU+o3rQldFdrFm8PIz0lXiSLyH2TvzEZiDToUX83n+Ubnb1vVNiLy/cKJIK9u2rVZB5NBIFH6Q+U+D63Q8qILjj9XhK497aIDrGXMZqdiBO5OEnY1RbzKT3wEC1uy0YmuQZLiBeuMCjFYqhi00RPeE4S5E3QaZC6CPyuBL4DNU6sVydtYxXp/c+fZvhdYb3PF4bH7KqERSWfmpEwyrcjD5xa7F7s7qauf+NbSB0XSBv/za8Tbbn4AIY3v4RjWSuyy/V0DmieOStOotgU0koho0HUolfsy8zFAqqaOoR4W0qziKXPGuy153iYNOb9Nnbkpa1Ek+/z3wwVspiDgSIO1f/r6VCBh5ve+xztQk0y83TULoDTrF6+KRvbA84ae1pCZBFCoVr4cMfCg7coteseD0S92R4M2n4eeQyGNBFOnJ1apnW1N7Wgh2t5o9oywtzIPqmX7ibGm+5q55kP3BI/JG+1RTHJfKfQIkKU2GCJuvwo/71rpKPemKzcQ9ZPGCEtzl/zzRXwhbsYHWZtVQiTjFVhDPz3BT70JMhDU2jsXQDz/TnTeWZJGq8OJKxm6ExDyG4T0zUUQ0z4UeUpi67W0tfqCaSWEhASpJv24Rj2RJImJ72NXuILQnFNR87FIjnH4Y9utnccyADHiUZKxK9+5Vj+T8fMJ9s=
    -
      # LTD_AWS_SECRET
      secure: OXg14yePTh5xx/zBeeR+OII9ndeXW7ph7SSNWPN3UinFLO41p693qYrQvyi5RS0iKDnNX5nS16VGX/z6AOvMk0Ykukc8QSp0/youMPZR/rAlzUD2IrxJp5hDdeNr2xTkCnOzabennnin1fAqMSklUmIqfCl6TAjk/nc8Hp2ux9PCkx4tSocwYmHCy+CU2ffw/ZWnaL2jgIRZxnNUjaVQHiVGVUYOFm/0I4Gp3ya+8rbLAOt9t0Nvgtczx4NDug9XwKYMwVhTnRtL97uebkzGCb0LA/7W0OpfNGO4Duf1TmWvZoGhA0nxXIG+nFJESni/dpyKbyF8j/rimngTG9TQpRoaWu3zUnj2fYMRmyxrTgv72G7nFe1UseGMIs8SaQLsFH2M3ocqgwfs3gLonF+h0qOQZXMoL207dFVdsPMJYxxuD100N/cXQsxuxuZZLiqWccZrVTfxdcxIAPQfhXpHnq7gaLbuzsiBdQFCdrVMaTS4TVdALE7NNkxntCjPXOf7Sx4BjdW8IRi04qH7NKFYcyl/6XhYqTZf/CsRo7jD6Jl5f+cL49Yl7peCFEPK9Rt1VrXCg4Po0slbY0YTn75dWuDHPsZdlmU/m2LSxXbk9YLHh9f6mJIweiMSZkwpudA66lWcB4+d1ZUG3QlNDVv6xK1sw+TccmNNFV0swXm/Y3A=
    -
      # LTD_USERNAME
      secure: chf6FPyyeY7uP7TQ4NxXIzKW/ICWvWkh4o9wuC2WZYNXi17jc9hR1I5ps4nKb6gU9Kka0xI6vTN+me9w26bi7ynw+yHwRHDDIu5tZjS44TnfxqvTtSfhC9qx873KFzFDrZ9ju7+86JYL3+xgu9CnTbfuN5DnVm9XC1D9lV9dcd9ONu03gsWT0Oy28ujw+ihNDK4aFHRg+NCeK3XJYnV+Q2EM+eJKZRVr/5azyc3/DRneJvuDe44roAlovByA4tcOauRIwUgqwRcv9R/knrgnGbnBCzNTWSAlw8UBefAdOHfCfmmsfnWDrLz3tY/f8eDqQnKSOP1YJz4yQQpyN1lE7WGDG0R0r+pi+N1bUs7c1LKOcxplPyij24nJjebBurK+dvf6uLGog7CxEZj7iC9TfSH9EzIWMIv2o9HiO0IxmtDuRkM5uCjDdEbZhZeFCK38JisXveJ5xVTvgY8xC82LcsDEQ7Uwciox3XN2dnC/VXZQ2blHaB/u68ZzvLAnkzwz518ajsQGqcGKJqntZwWO0I0FtxSXfy8oHQ/IOHSn2ixIxEyhEzJSIs9T4QLXWGv4Lx39JqsG3zslcXDwVNxxULicBdat0qnwlAb/w2U11A79GGhU0HowZS3BmWtZeUj1gJd0kKWYPdn7P1pxgNu/nMt0zpSqy/HAqND85fJJKAU=
    -
      # LTD_PASSWORD
      secure: mWnoUVgok0hp9rco0ofc8dr8WK1qWH5fiEvtZAHLMXAiVlRH16qenpKdQI/iLYXHB1rDaB7WmpBhmmgc1POoXIkND8Add78gtYXduFcdJu6PIpNMtX8k3jj+LX9I9IYhYiS9ZSWM5GhJ4vfKUsiI22ywJkxqnlYCjyrjR8XmaADzcsDVfPgyjtWVFcyOnq5cRWGaD5F1sXeUoKEp/HoOSzbjs+FCYipLKRV6rwh0tfWFCpfFpQrwqs6gqAJNpqG2GsCSW8Pa6GQii4KMymGo8XG+hqW4rQmJR2GxNm6MegqYIa+EqOVd69dbrgWQ8o4g2ZHg5xqCwpvuY3QvX8qdYO1pvV2UTDw/c2feCf6P41OGJfWwG8p925KPNUgXu3oCVn3wQiN9hl4e50aaQ+87RSgN1R3H4anl6r3iT4Va/IUoLSvSnpphjvKkNPnVPtqRmsBOc4gcKSzjmJ18IvOFpogSYbkr7mpjEUDi6UG2vIlugJ8qeX7RX04wBT+huYgBUIYfWQuFaInG9zlLM4KGjnfF3KKxiYUrgwLEjgA9w0yGWDwevbT7Z3CjshrhBeHXb2aqErQ1QusSwlX/tAIquLI22fBOtgfVQtQrAF9d70aDcEk2PrtpSi6AczJBQB0X+Wo4Xf0umsY+0qYgmlsRmFW8kr+4Dy3qULz0Wx0RjWc=
